//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Functionland.FxFiles.Client.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Functionland.FxFiles.Client.Shared.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to pinned items.
        /// </summary>
        public static string AddPinnedItems {
            get {
                return ResourceManager.GetString("AddPinnedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        public static string Artifact {
            get {
                return ResourceManager.GetString("Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact already dose not pinned. .
        /// </summary>
        public static string ArtifactAlreadyDoseNotPinnedException {
            get {
                return ResourceManager.GetString("ArtifactAlreadyDoseNotPinnedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already  contains  an item  with the same name..
        /// </summary>
        public static string ArtifactAlreadyExistsException {
            get {
                return ResourceManager.GetString("ArtifactAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} already pinned.
        /// </summary>
        public static string ArtifactAlreadyPinnedException {
            get {
                return ResourceManager.GetString("ArtifactAlreadyPinnedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} dose not exists exception.
        /// </summary>
        public static string ArtifactDoseNotExistsException {
            get {
                return ResourceManager.GetString("ArtifactDoseNotExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} name has invalid chars..
        /// </summary>
        public static string ArtifactNameHasInvalidChars {
            get {
                return ResourceManager.GetString("ArtifactNameHasInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in the item name..
        /// </summary>
        public static string ArtifactNameHasInvalidCharsException {
            get {
                return ResourceManager.GetString("ArtifactNameHasInvalidCharsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} name is empty.
        /// </summary>
        public static string ArtifactNameIsNull {
            get {
                return ResourceManager.GetString("ArtifactNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered any name..
        /// </summary>
        public static string ArtifactNameIsNullException {
            get {
                return ResourceManager.GetString("ArtifactNameIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} path is null.
        /// </summary>
        public static string ArtifactPathIsNull {
            get {
                return ResourceManager.GetString("ArtifactPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact type is null.
        /// </summary>
        public static string ArtifactTypeIsNull {
            get {
                return ResourceManager.GetString("ArtifactTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        public static string ArtifactUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("ArtifactUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AutomaticContent {
            get {
                return ResourceManager.GetString("AutomaticContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blox is not found.
        /// </summary>
        public static string BloxIsNotFoundException {
            get {
                return ResourceManager.GetString("BloxIsNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Modified 09/30/22.
        /// </summary>
        public static string BloxModified {
            get {
                return ResourceManager.GetString("BloxModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Blox Setup.
        /// </summary>
        public static string BloxName {
            get {
                return ResourceManager.GetString("BloxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already a member of this poolblox.
        /// </summary>
        public static string BloxPoolAlreadyExistsException {
            get {
                return ResourceManager.GetString("BloxPoolAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blox pool is not found.
        /// </summary>
        public static string BloxPoolIsNotFoundException {
            get {
                return ResourceManager.GetString("BloxPoolIsNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        public static string ButtonAddFile {
            get {
                return ResourceManager.GetString("ButtonAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new folder.
        /// </summary>
        public static string ButtonAddNewFolder {
            get {
                return ResourceManager.GetString("ButtonAddNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ButtonSearchFullWidth {
            get {
                return ResourceManager.GetString("ButtonSearchFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        public static string ButtonUploadFiles {
            get {
                return ResourceManager.GetString("ButtonUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelModal {
            get {
                return ResourceManager.GetString("CancelModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not operate on files exception.
        /// </summary>
        public static string CanNotOperateOnFilesException {
            get {
                return ResourceManager.GetString("CanNotOperateOnFilesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf.
        /// </summary>
        public static string CardFileFormat {
            get {
                return ResourceManager.GetString("CardFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation_document.
        /// </summary>
        public static string CardFileName {
            get {
                return ResourceManager.GetString("CardFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.22 mb.
        /// </summary>
        public static string CardFileSize {
            get {
                return ResourceManager.GetString("CardFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be processed because of conflict in the request.
        /// </summary>
        public static string ConflicException {
            get {
                return ResourceManager.GetString("ConflicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files.
        /// </summary>
        public static string CopyFiles {
            get {
                return ResourceManager.GetString("CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy here.
        /// </summary>
        public static string CopyHere {
            get {
                return ResourceManager.GetString("CopyHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to.
        /// </summary>
        public static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item will be permanently deleted from your device. Are you sure you want to delete this item?.
        /// </summary>
        public static string DeleteItemDescription {
            get {
                return ResourceManager.GetString("DeleteItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} item.
        /// </summary>
        public static string DeleteItems {
            get {
                return ResourceManager.GetString("DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These items will be permanently deleted from your device. Are you sure you want to delete these items?.
        /// </summary>
        public static string DeleteItemsDescription {
            get {
                return ResourceManager.GetString("DeleteItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting files.
        /// </summary>
        public static string DeletingFiles {
            get {
                return ResourceManager.GetString("DeletingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete drive.
        /// </summary>
        public static string DriveRemoveFailed {
            get {
                return ResourceManager.GetString("DriveRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not rename drive.
        /// </summary>
        public static string DriveRenameFailed {
            get {
                return ResourceManager.GetString("DriveRenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here.
        /// </summary>
        public static string EmptyListTitle {
            get {
                return ResourceManager.GetString("EmptyListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External storage.
        /// </summary>
        public static string ExternalStorageName {
            get {
                return ResourceManager.GetString("ExternalStorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip file name.
        /// </summary>
        public static string ExtractFolderTargetNamePlaceHolder {
            get {
                return ResourceManager.GetString("ExtractFolderTargetNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract here.
        /// </summary>
        public static string ExtractHere {
            get {
                return ResourceManager.GetString("ExtractHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting folder.
        /// </summary>
        public static string ExtractingFolder {
            get {
                return ResourceManager.GetString("ExtractingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password for the zip file.
        /// </summary>
        public static string ExtractPasswordModalTitle {
            get {
                return ResourceManager.GetString("ExtractPasswordModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perferendis blanditiis modi amet architecto voluptatem animi saepe non?.
        /// </summary>
        public static string FieldQuestionInput {
            get {
                return ResourceManager.GetString("FieldQuestionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileAlreadyExistsException.
        /// </summary>
        public static string FileAlreadyExistsException {
            get {
                return ResourceManager.GetString("FileAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zip file dose not found..
        /// </summary>
        public static string FileNotFoundException {
            get {
                return ResourceManager.GetString("FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing file.
        /// </summary>
        public static string FileRemoveFailed {
            get {
                return ResourceManager.GetString("FileRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileRenamePlaceholder {
            get {
                return ResourceManager.GetString("FileRenamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files &amp; Blox hardware.
        /// </summary>
        public static string FilesAndBloxHardware {
            get {
                return ResourceManager.GetString("FilesAndBloxHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading file.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        public static string FolderRenamePlaceholder {
            get {
                return ResourceManager.GetString("FolderRenamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder size.
        /// </summary>
        public static string FolderSize {
            get {
                return ResourceManager.GetString("FolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the requested resource is forbidden.
        /// </summary>
        public static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature will come in near future.
        /// </summary>
        public static string FutureFeature {
            get {
                return ResourceManager.GetString("FutureFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fx Files.
        /// </summary>
        public static string FxFiles {
            get {
                return ResourceManager.GetString("FxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive.
        /// </summary>
        public static string GoogleDrive {
            get {
                return ResourceManager.GetString("GoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact not been shared.
        /// </summary>
        public static string HasNotBeenSharedException {
            get {
                return ResourceManager.GetString("HasNotBeenSharedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple message in home.
        /// </summary>
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from apps.
        /// </summary>
        public static string ImportFromApps {
            get {
                return ResourceManager.GetString("ImportFromApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in “{0}”.
        /// </summary>
        public static string InputSearchFullWidth {
            get {
                return ResourceManager.GetString("InputSearchFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your files.
        /// </summary>
        public static string InputSearchParial {
            get {
                return ResourceManager.GetString("InputSearchParial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal storage.
        /// </summary>
        public static string InternalStorageName {
            get {
                return ResourceManager.GetString("InternalStorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is invalid..
        /// </summary>
        public static string InvalidPasswordException {
            get {
                return ResourceManager.GetString("InvalidPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip file not supported: {0}.
        /// </summary>
        public static string InvalidZipExtensionException {
            get {
                return ResourceManager.GetString("InvalidZipExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items selected.
        /// </summary>
        public static string ItemsSelected {
            get {
                return ResourceManager.GetString("ItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known error.
        /// </summary>
        public static string KnownException {
            get {
                return ResourceManager.GetString("KnownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s go.
        /// </summary>
        public static string LetsGo {
            get {
                return ResourceManager.GetString("LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified 09/30/22.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving files.
        /// </summary>
        public static string MoveFileModal {
            get {
                return ResourceManager.GetString("MoveFileModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move here.
        /// </summary>
        public static string MoveHere {
            get {
                return ResourceManager.GetString("MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving files.
        /// </summary>
        public static string MovingFiles {
            get {
                return ResourceManager.GetString("MovingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Device.
        /// </summary>
        public static string MyDevice {
            get {
                return ResourceManager.GetString("MyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolderPlaceholder {
            get {
                return ResourceManager.GetString("NewFolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextSlide {
            get {
                return ResourceManager.GetString("NextSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported encrypted file.
        /// </summary>
        public static string NotSupportedEncryptedFileException {
            get {
                return ResourceManager.GetString("NotSupportedEncryptedFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding.
        /// </summary>
        public static string Onboarding {
            get {
                return ResourceManager.GetString("Onboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password did not match..
        /// </summary>
        public static string PasswordDidNotMatchedException {
            get {
                return ResourceManager.GetString("PasswordDidNotMatchedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the path is null.
        /// </summary>
        public static string PathIsNull {
            get {
                return ResourceManager.GetString("PathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Description.
        /// </summary>
        public static string PlaceHolderFilledTextInput {
            get {
                return ResourceManager.GetString("PlaceHolderFilledTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pools.
        /// </summary>
        public static string Pools {
            get {
                return ResourceManager.GetString("Pools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev..
        /// </summary>
        public static string PreviousSlide {
            get {
                return ResourceManager.GetString("PreviousSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from pinned items.
        /// </summary>
        public static string RemoveFromPinnedItems {
            get {
                return ResourceManager.GetString("RemoveFromPinnedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace {0} item(s) .
        /// </summary>
        public static string ReplaceButtonModal {
            get {
                return ResourceManager.GetString("ReplaceButtonModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        public static string ReplaceOrSkipSubDescModal {
            get {
                return ResourceManager.GetString("ReplaceOrSkipSubDescModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder already has {0} item(s) with the same name,.
        /// </summary>
        public static string ReplaceOrSkipSupDescModal {
            get {
                return ResourceManager.GetString("ReplaceOrSkipSupDescModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace or skip {0} item(s).
        /// </summary>
        public static string ReplaceOrSkipTitleModal {
            get {
                return ResourceManager.GetString("ReplaceOrSkipTitleModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing files.
        /// </summary>
        public static string ReplacingFiles {
            get {
                return ResourceManager.GetString("ReplacingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid.
        /// </summary>
        public static string ResourceValidationException {
            get {
                return ResourceManager.GetString("ResourceValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating with server.
        /// </summary>
        public static string RestException {
            get {
                return ResourceManager.GetString("RestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder can not be deleted.
        /// </summary>
        public static string RootFolderDeleteException {
            get {
                return ResourceManager.GetString("RootFolderDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder cannot be renamed.
        /// </summary>
        public static string RootfolderRenameException {
            get {
                return ResourceManager.GetString("RootfolderRenameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination file is the same as the source file..
        /// </summary>
        public static string SameDestinationFileException {
            get {
                return ResourceManager.GetString("SameDestinationFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder is the same as the source folder..
        /// </summary>
        public static string SameDestinationFolderException {
            get {
                return ResourceManager.GetString("SameDestinationFolderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card ({0}).
        /// </summary>
        public static string SDCardName {
            get {
                return ResourceManager.GetString("SDCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See details .
        /// </summary>
        public static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fx Files by Functionland.
        /// </summary>
        public static string SettingPageAppTitle {
            get {
                return ResourceManager.GetString("SettingPageAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup complete.
        /// </summary>
        public static string SetupComplete {
            get {
                return ResourceManager.GetString("SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        public static string SharedFileCardTag {
            get {
                return ResourceManager.GetString("SharedFileCardTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with app.
        /// </summary>
        public static string ShareWithApp {
            get {
                return ResourceManager.GetString("ShareWithApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show in location.
        /// </summary>
        public static string ShowInLocation {
            get {
                return ResourceManager.GetString("ShowInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip {0} item(s).
        /// </summary>
        public static string SkipButtonModal {
            get {
                return ResourceManager.GetString("SkipButtonModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        public static string Specter {
            get {
                return ResourceManager.GetString("Specter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream file is null.
        /// </summary>
        public static string StreamFileIsNull {
            get {
                return ResourceManager.GetString("StreamFileIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be backedup in following:.
        /// </summary>
        public static string SuccessfullLoginBloxBackup {
            get {
                return ResourceManager.GetString("SuccessfullLoginBloxBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Login was successful To Fula.
        /// </summary>
        public static string SuccessfulLoginMessage {
            get {
                return ResourceManager.GetString("SuccessfulLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system light/dark mode setting..
        /// </summary>
        public static string SystemThemeDescription {
            get {
                return ResourceManager.GetString("SystemThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Label.
        /// </summary>
        public static string TagLabel {
            get {
                return ResourceManager.GetString("TagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test explorer.
        /// </summary>
        public static string TestExplorer {
            get {
                return ResourceManager.GetString("TestExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string TextAreaLabel {
            get {
                return ResourceManager.GetString("TextAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type message here....
        /// </summary>
        public static string TextAreaPlaceholder {
            get {
                return ResourceManager.GetString("TextAreaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items copied.
        /// </summary>
        public static string TheCopyOpreationSuccessedMessage {
            get {
                return ResourceManager.GetString("TheCopyOpreationSuccessedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your item(s) has been copied.
        /// </summary>
        public static string TheCopyOpreationSuccessedTiltle {
            get {
                return ResourceManager.GetString("TheCopyOpreationSuccessedTiltle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items moved.
        /// </summary>
        public static string TheMoveOpreationSuccessedMessage {
            get {
                return ResourceManager.GetString("TheMoveOpreationSuccessedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your item(s) has been moved.
        /// </summary>
        public static string TheMoveOpreationSuccessedTiltle {
            get {
                return ResourceManager.GetString("TheMoveOpreationSuccessedTiltle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed.
        /// </summary>
        public static string TheOpreationFailedMessage {
            get {
                return ResourceManager.GetString("TheOpreationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the app is available for download..
        /// </summary>
        public static string ToastDescMessage {
            get {
                return ResourceManager.GetString("ToastDescMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your error message.
        /// </summary>
        public static string ToastErrorMessage {
            get {
                return ResourceManager.GetString("ToastErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string ToastErrorTitle {
            get {
                return ResourceManager.GetString("ToastErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your info message.
        /// </summary>
        public static string ToastInfoMessage {
            get {
                return ResourceManager.GetString("ToastInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your success message.
        /// </summary>
        public static string ToastSuccessMessage {
            get {
                return ResourceManager.GetString("ToastSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your warning message.
        /// </summary>
        public static string ToastWarningMessage {
            get {
                return ResourceManager.GetString("ToastWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        public static string TooManyRequestsExceptions {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow permission for storage access!.
        /// </summary>
        public static string UnableToAccessToStorage {
            get {
                return ResourceManager.GetString("UnableToAccessToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load storge manager..
        /// </summary>
        public static string UnableToLoadStorageManager {
            get {
                return ResourceManager.GetString("UnableToLoadStorageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request lacks valid authentication credentials.
        /// </summary>
        public static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error has occurred.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file provider for path: {0}.
        /// </summary>
        public static string UnknownFsFileProviderException {
            get {
                return ResourceManager.GetString("UnknownFsFileProviderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was modified by another user after you got the original data. the operation was canceled..
        /// </summary>
        public static string UpdateConcurrencyException {
            get {
                return ResourceManager.GetString("UpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Fula.
        /// </summary>
        public static string WelcomePageConnectContent {
            get {
                return ResourceManager.GetString("WelcomePageConnectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et ex nam hic qui minima neque dolore sunt repellendus. Commodi explicabo qui..
        /// </summary>
        public static string WelcomePageDesc {
            get {
                return ResourceManager.GetString("WelcomePageDesc", resourceCulture);
            }
        }
    }
}
