//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Functionland.FxFiles.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Functionland.FxFiles.Shared.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} already exists exception.
        /// </summary>
        public static string ArtifactAlreadyExistsException {
            get {
                return ResourceManager.GetString("ArtifactAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} name is null.
        /// </summary>
        public static string ArtifactNameIsNull {
            get {
                return ResourceManager.GetString("ArtifactNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} path is null.
        /// </summary>
        public static string ArtifactPathIsNull {
            get {
                return ResourceManager.GetString("ArtifactPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artifact type is null.
        /// </summary>
        public static string ArtifactTypeIsNull {
            get {
                return ResourceManager.GetString("ArtifactTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ButtonSearchFullWidth {
            get {
                return ResourceManager.GetString("ButtonSearchFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not operate on files exception.
        /// </summary>
        public static string CanNotOperateOnFilesException {
            get {
                return ResourceManager.GetString("CanNotOperateOnFilesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be processed because of conflict in the request.
        /// </summary>
        public static string ConflicException {
            get {
                return ResourceManager.GetString("ConflicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete drive.
        /// </summary>
        public static string DriveRemoveFailed {
            get {
                return ResourceManager.GetString("DriveRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileAlreadyExistsException.
        /// </summary>
        public static string FileAlreadyExistsException {
            get {
                return ResourceManager.GetString("FileAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing file.
        /// </summary>
        public static string FileRemoveFailed {
            get {
                return ResourceManager.GetString("FileRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files &amp; Blox hardware.
        /// </summary>
        public static string FilesAndBloxHardware {
            get {
                return ResourceManager.GetString("FilesAndBloxHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading file.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the requested resource is forbidden.
        /// </summary>
        public static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple message in home.
        /// </summary>
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title of home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in “folder name”.
        /// </summary>
        public static string InputSearchFullWidth {
            get {
                return ResourceManager.GetString("InputSearchFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your files.
        /// </summary>
        public static string InputSearchParial {
            get {
                return ResourceManager.GetString("InputSearchParial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        public static string internalStorageName {
            get {
                return ResourceManager.GetString("internalStorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known error.
        /// </summary>
        public static string KnownException {
            get {
                return ResourceManager.GetString("KnownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Device.
        /// </summary>
        public static string MyDevice {
            get {
                return ResourceManager.GetString("MyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the path is null.
        /// </summary>
        public static string PathIsNull {
            get {
                return ResourceManager.GetString("PathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pools.
        /// </summary>
        public static string Pools {
            get {
                return ResourceManager.GetString("Pools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid.
        /// </summary>
        public static string ResourceValidationException {
            get {
                return ResourceManager.GetString("ResourceValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating with server.
        /// </summary>
        public static string RestException {
            get {
                return ResourceManager.GetString("RestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Card ({0}).
        /// </summary>
        public static string SDCardName {
            get {
                return ResourceManager.GetString("SDCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream file is null.
        /// </summary>
        public static string StreamFileIsNull {
            get {
                return ResourceManager.GetString("StreamFileIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the app is available for download..
        /// </summary>
        public static string ToastDescMessage {
            get {
                return ResourceManager.GetString("ToastDescMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your error message.
        /// </summary>
        public static string ToastErrorMessage {
            get {
                return ResourceManager.GetString("ToastErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your info message.
        /// </summary>
        public static string ToastInfoMessage {
            get {
                return ResourceManager.GetString("ToastInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your success message.
        /// </summary>
        public static string ToastSuccessMessage {
            get {
                return ResourceManager.GetString("ToastSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your warning message.
        /// </summary>
        public static string ToastWarningMessage {
            get {
                return ResourceManager.GetString("ToastWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        public static string TooManyRequestsExceptions {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load storge manager..
        /// </summary>
        public static string UnableToLoadStorageManager {
            get {
                return ResourceManager.GetString("UnableToLoadStorageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request lacks valid authentication credentials.
        /// </summary>
        public static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error has occurred.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file provider for path: {0}.
        /// </summary>
        public static string UnknownFsFileProviderException {
            get {
                return ResourceManager.GetString("UnknownFsFileProviderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was modified by another user after you got the original data. the operation was canceled..
        /// </summary>
        public static string UpdateConcurrencyException {
            get {
                return ResourceManager.GetString("UpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string Zones {
            get {
                return ResourceManager.GetString("Zones", resourceCulture);
            }
        }
    }
}
